### PR TITLE
Feature/2fa

### PR DESCRIPTION
**Pull request by b1scuit-thi3f**
Feature request as per #31 
This uses the onetimepass Python library as I realised I was just inventing the wheel. Handles users either having or not having a OTP set, as well regenerating and viewing a QR-code version of the secret.
Possibly needs some more work in the feature to make it look a bit neater, but I think it does what it needs to intially.

### CODE REVIEW

**Comment by z1pti3** [comment]
Looks good, do you have a license file for the js library?

**Comment by b1scuit-thi3f** [comment]
Yep, not sure where you want it but here it is!
https://github.com/kazuhikoarase/qrcode-generator/blob/master/LICENSE

**Comment by z1pti3** [comment]
> Yep, not sure where you want it but here it is!
> https://github.com/kazuhikoarase/qrcode-generator/blob/master/LICENSE

web/licenses

I only collected these as we have bundled them into the application, the python ones will be included in the pip repos for users to get hold of and read if needed.

**Comment by b1scuit-thi3f** [comment]
Cool, I'll add that now. Will close off this branch anyway.

**Comment by z1pti3** [comment]
I think we also need to update requirements.txt

**Pull request merged**
