### PR TITLE
Feature/subflow retry

### LINKED ISSUE #262: [Feature] subFlow retry option
It would be really good if subFlow had a retry and retry delay option so that subFlows that do not return True can be attempted again. 

For this to work subFlow will need an object to be set when a flow is to be considered successful like playbookEnd but could just be a VAR or DATA object that is passed back to the main flow?

### PR DESCRIPTION
**Pull request by b1scuit-thi3f**
Allows for the retrying of subflows. Currently there are two values that can now be set; maxRetries and retryDelay.
image
This allows a user to ask jimi to retry the subflow but also wait a certain period of time between each. User's will have to keep in mind the total trigger time.

In order for subflow to know whether it was a success or not, currently users can add the following varDefinition anywhere in the child flow and this will be checked by subflow:
**{"subflowResult":{"value":false|true}}**
```
if "subflowResult" in finalData["flowData"]["var"]:
	subflowResult = finalData["flowData"]["var"]["subflowResult"]
```

### CODE REVIEW

**Comment by u-n-i-c-o-rn** [comment]
Do you think we should have an object that defines this like a subFlow return object which exists the subFlow at the sametime?

**Comment by b1scuit-thi3f** [comment]
@u-n-i-c-o-rn I was thinking that maybe this should be the alternative option. Maybe we look at implementing both for now and then remove one should it be unused.

**Comment by u-n-i-c-o-rn** [comment]
Should we make both do the same thing but just have one in object form that also does a return / exit and the other is just setting the var and letting it return on its own?

**Comment by z1pti3** [comment]
I have made some minor bug fixes as if you return true it runs forever till the flow is killed. 

Also a new action subFlowReturn is now added that makes returning more user friendly - it also breaks the subflow at that given point.

**Review by z1pti3 — APPROVED** [review]

**Pull request merged**
